# Spring配置
spring:
  application:
    name: Question Answer Management System
  # 环境配置
  profiles:
    active: @profileActive@

# 项目相关配置
fcms:
  # 名称
  name: fcms
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2022